qbox server one way connection

diff --git a/QBox/QBox b/QBox/QBox
--- a/QBox/QBox
+++ b/QBox/QBox
@@ -235,7 +235,8 @@ case $1 in
 			
 			declare -a msg_arr=("[${pid_t}]using_host_ip:${host_ip_t}" "[${pid_t}]starting_httpd..." \
 							"[${pid_t}]httpd_started_at_${tm_t}..." "[${pid_t}]httpd_listening_on_port_4020" \
-							"[${pid_QS}]starting_QBox_server..." "[${pid_QS}]QBox_server_on_port_4040..." "[$pid_QS]QBox_server_started_at_$(date +%T)..." \
+							"[${pid_QS}]starting_QBox_server..." "[${pid_QS}]QBox_server_on_port_4040..." \
+							"[${pid_QS}]getting_qbox_server_pid..." "[$pid_QS]QBox_server_started_at_$(date +%T)..." \
 							"[${pid_t}]trying_to_open_browser..." "[${pid_t}]Access:http://${host_ip_t}:4020" )
 								
 			[ ${pid_t} -ne -1  ] && {
@@ -243,13 +244,15 @@ case $1 in
 					echo -e "${msg_arr[$index]//_/ }"
 					sleep 2
 						
-					[ $index -eq 4 ] && {
-						pid_QS=$(qbox_server_start)
-						echo $pid_QS >$HOME/my_script/QB/v.txt
-						[ ${pid_QS} -eq -1 ] && { echo "[$$]QBox server failed to start..."; }
+					[ $index -eq 4 ] && { qbox_server_start; }
+					
+					[ $index -eq 6 ] && {
+						pid_QS=$(get_qboxServer_pid)
+						
+						[ $pid_QS -eq -1 ] && { echo "qbox server could not start"; kill -9 ${pid_t} 2>/dev/null; exit 1; }
 					}
 					
-					[ $index -eq 7 ] && {
+					[ $index -eq 8 ] && {
 						
 						if [ "${host_ip_t}" = "127.0.0.1" ] || [ "${host_ip_t}" = "localhost" ]; then
 							browser=$(which xdg-open || which gnome-open ) && {
@@ -258,7 +261,7 @@ case $1 in
 						fi
 					}
 						
-					[ $index -eq 8 ] && { 
+					[ $index -eq 9 ] && { 
 						echo "${pid_t}|${tm_t}|http://${host_ip_t}:4020|${pid_QS}">${test_serv_running}
 						
 						#pressing any key to exit
@@ -278,7 +281,7 @@ case $1 in
 			url=$(return_n_field ${test_serv_running} 3 "|")
 			pid_QS=$(return_n_field ${test_serv_running} 4 "|")
 			
-			printf "Server already started at %s with pids of %d  on url %s\n" "${tm_t}" ${pid_t} "${url}" 
+			printf "Server already started at ${tm_t} with pids of ${pid_t} ${pid_QS} on url ${url} \n"
 			echo -n "Do you want to stop the server?[y/[N]]"
 			read -n 1
 
