qbox thread library and notification system not working

diff --git a/QBox/include_dir/include b/QBox/include_dir/include
--- a/QBox/include_dir/include
+++ b/QBox/include_dir/include
@@ -857,188 +857,207 @@ elif [[ $1 = "<basic_utils.h>" ]]; then
 		return ${test_ip}	
 	}
 
-##Test whether input is char 
-function isdigit(){
-	if [ -z "$1" ]; then
-		return 	$FAILURE
-	fi 
-	
-	case "$1" in 
-		[[:digit:]]|[[:digit:]]*) return $SUCCESS ;;
-		*)	return $FAILURE ;;
-	esac
-}
-
-##Verify IP address format
-function is_IP_Valid(){
-	
-	local _return=${FAILURE}
-	
-	if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]]; then
-		OLDIFS=${IFS}
-		IFS="."
-		declare -a IP=($1)
-		IFS=${OLDIFS}
-		[[ ${IP[0]} -le 255 ]] && [[ ${IP[1]} -le 255 ]] && [[ ${IP[2]} -le 255 ]] && [[ ${IP[3]} -le 255 ]] && {
-			_return=${SUCCESS}
-		}
-	fi 
-	
-	return $_return
-}	
-
-## verify macaddress
-function is_valid_macaddr() {
-	local test_mac=${FAILURE}
-	
-	if [[ $1 =~ [[:xdigit:]][[:xdigit:]]:[[:xdigit:]][[:xdigit:]]:[[:xdigit:]][[:xdigit:]]:[[:xdigit:]][[:xdigit:]]:[[:xdigit:]][[:xdigit:]]:[[:xdigit:]][[:xdigit:]] ]]; then
-		test_mac=${SUCCESS}
-	fi 	
-	
-	return ${test_mac}
-}
-
-function is_valid_VLAN() {
-	local test_vlan=${FAILURE}
-	
-	if isdigit $1 && [ $1 -ge 0 ] && [ $1 -le 1000 ]; then
-		test_vlan=${SUCCESS}
-	fi	
-	return ${test_vlan}
-}
-
-##is valid file descriptor
-function is_valid_fd() {
-	local test_fd=${FAILURE}
-	
-	if isdigit $1 && [ $1 -ge 0 ] && [ $1 -le 1000 ]; then
-		test_fd=${SUCCESS}
-	fi		
-	
-	return ${test_fd}
-}
-
-##unique for the vms. The name is used as the primary key for vms database
-function is_VMName_unique(){
-	local _return=${FAILURE}
-	
-	if check_is_set $(String_to_Upper $1) ; then
-		local search="^$1\$"
-		local unique=$(gawk -F "|" -v var=$search '$1 ~ var {print $1}' ${QDB_FOLDER}/vms.qdb 2>/dev/null)
-		[ -z ${unique} ] && _return=${SUCCESS}
-	fi 
-	
-	return ${_return}
-}
-
-#ret: array of path to iso files
-function check_for_iso_files() {
-	local -a iso_files=
-	local index=0
-	for iso in $(find ${HOME} -depth -type f -a -name "*.iso" -print 2>>/dev/null); do 
-		iso_files[$index]=$iso
-		(( index++ ))
-	done
-	
-	echo -n ${iso_files[@]}
-}
-
-function disk_size_valid(){
-#Sat 28 Jan 2017 12:18:24 AM GMT 
-	local tmp=$1
-	if [[ -z "$1" ]]; then
-		return ${FAILURE}
-	fi 
-	
-	local first_part=${tmp%%[[:alpha:]]*}
-	local second_part=${tmp##*[[:digit:]]}
-	
-	isdigit ${first_part} && [[ ${first_part} -ge 1 ]] && [[ ${second_part} =~ [[:alpha:]] ]] && [[ "${second_part}" = "G" || "${second_part}" = "M" ]] && { return ${SUCCESS}; } 
-	
-	return ${FAILURE}
-}
-
-function is_valid_port_num() {
-	local test_port=${FAILURE}
-	
-	if isdigit $1 && [ $1 -ge 1 ] && [ $1 -le 65535 ]; then
-		test_port=${SUCCESS}
-	fi 			
-	return ${test_port}
-}
-
-#argu: Test_variable:Name_configuration_part_to_test
-function _test_already_configured() {
-	local _ret=${SUCCESS}
-	
-	if [[ ${1%%:*} -eq ${SUCCESS} ]]; then
-		NOT_DEFINE ${__CMDLINE__} && {
-			${DIALOG} \
-				--colors --title "\Zb\Z1Already Configured\Zn\ZB" --yesno "Already configured:\Zb\Z1${1##*:}\Zn\ZB.\nDo you want to reconfigure?" \
-				$((HEIGHT-7)) $((WIDTH-20))
-				
-			case $? in 
-				${DIALOG_OK}) _ret=${SUCCESS} ;;
-				${DIALOG_CANCEL}) _ret=${FAILURE} ;;
-			esac
-		} || {
-			tput setaf 9
-			echo -en $(get_string_by_name COND_ALREADY_CONFIGURED "${1##*:}[y/N]?")
-			tput sgr0
-			read -n 1 ans
-			
-			case "$ans" in 
-				Y|y) _ret=${SUCCESS} ;;
-				*) _ret=${FAILURE} ;;
-			esac 
-		}
-	fi 
-	
-	return $_ret
-}
-
-#argu: test_condition:display_text
-function _check_configured() {
-	local -a _argu_arr=( $@ )
-	local _configured=${FAILURE}
-	local msg_str=""
-	
-	for (( index=0; index<${#_argu_arr[@]}; index++ )); do 
-		if [[ ${_argu_arr[$index]%%:*} -eq ${FAILURE} ]]; then
-			msg_str+=${_argu_arr[$index]##*:}
-			_configured=${SUCCESS}
+	##Test whether input is char 
+	function isdigit(){
+		if [ -z "$1" ]; then
+			return 	$FAILURE
 		fi 
-	done 
 	
-	[ ${_configured} -eq ${SUCCESS} ] && {
-		msg_str=${msg_str//_/ }
-		msg_str=${msg_str//|/\\n}
+		case "$1" in 
+			[[:digit:]]|[[:digit:]]*) return $SUCCESS ;;
+			*)	return $FAILURE ;;
+		esac
+	}
+
+	##Verify IP address format
+	function is_IP_Valid(){
+	
+		local _return=${FAILURE}
+	
+		if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]]; then
+			OLDIFS=${IFS}
+			IFS="."
+			declare -a IP=($1)
+			IFS=${OLDIFS}
+			[[ ${IP[0]} -le 255 ]] && [[ ${IP[1]} -le 255 ]] && [[ ${IP[2]} -le 255 ]] && [[ ${IP[3]} -le 255 ]] && {
+				_return=${SUCCESS}
+			}
+		fi 
+	
+		return $_return
+	}	
+
+	## verify macaddress
+	function is_valid_macaddr() {
+		local test_mac=${FAILURE}
+	
+		if [[ $1 =~ [[:xdigit:]][[:xdigit:]]:[[:xdigit:]][[:xdigit:]]:[[:xdigit:]][[:xdigit:]]:[[:xdigit:]][[:xdigit:]]:[[:xdigit:]][[:xdigit:]]:[[:xdigit:]][[:xdigit:]] ]]; then
+			test_mac=${SUCCESS}
+		fi 	
+	
+		return ${test_mac}
+	}
+
+	function is_valid_VLAN() {
+		local test_vlan=${FAILURE}
+	
+		if isdigit $1 && [ $1 -ge 0 ] && [ $1 -le 1000 ]; then
+			test_vlan=${SUCCESS}
+		fi	
+		return ${test_vlan}
+	}
+
+	##is valid file descriptor
+	function is_valid_fd() {
+		local test_fd=${FAILURE}
+	
+		if isdigit $1 && [ $1 -ge 0 ] && [ $1 -le 1000 ]; then
+			test_fd=${SUCCESS}
+		fi		
+	
+		return ${test_fd}
+	}
+
+	##unique for the vms. The name is used as the primary key for vms database
+	function is_VMName_unique(){
+		local _return=${FAILURE}
+	
+		if check_is_set $(String_to_Upper $1) ; then
+			local search="^$1\$"
+			local unique=$(gawk -F "|" -v var=$search '$1 ~ var {print $1}' ${QDB_FOLDER}/vms.qdb 2>/dev/null)
+			[ -z ${unique} ] && _return=${SUCCESS}
+		fi 
+	
+		return ${_return}
+	}
+
+	#ret: array of path to iso files
+	function check_for_iso_files() {
+		#local -a iso_files=
+		#local index=0
+		local dir_=
+	
+		[ -n $1 ] && { 
+			dir_=$(gawk -F "|" -v var="^$1\$" '$1 ~ var {print $2}' $INPUT_PIPE)
+		} || { dir_=${HOME}; }
 		
-		NOT_DEFINE ${__CMDLINE__} && { 
-			${DIALOG} \
-				--colors --title "\Zb\Z1 Not Configured Yet\Zn\ZB" --msgbox "You have not configured.\n \Zb\Z1${msg_str}\Zn\ZB." \
-				$((HEIGHT-7)) $((WIDTH-20))		
-		} || { 
-			tput setaf 9
-			echo -en "\nYou have not configured.\n$msg_str"
-			tput sgr0
+		for iso in $(find ${dir_} -maxdepth 1 -type f -a -name "*.iso" -print 2>>/dev/null); do 
+			#iso_files[$index]=$iso
+			#(( index++ ))
+			echo $iso >OUTPUT_PIPE &
+		done
+	
+		#echo -n ${iso_files[@]}
+	}
+
+	function disk_size_valid(){
+	#Sat 28 Jan 2017 12:18:24 AM GMT 
+		local tmp=$1
+		if [[ -z "$1" ]]; then
+			return ${FAILURE}
+		fi 
+	
+		local first_part=${tmp%%[[:alpha:]]*}
+		local second_part=${tmp##*[[:digit:]]}
+	
+		isdigit ${first_part} && [[ ${first_part} -ge 1 ]] && [[ ${second_part} =~ [[:alpha:]] ]] && [[ "${second_part}" = "G" || "${second_part}" = "M" ]] && { return ${SUCCESS}; } 
+	
+		return ${FAILURE}
+	}
+
+	function is_valid_port_num() {
+		local test_port=${FAILURE}
+	
+		if isdigit $1 && [ $1 -ge 1 ] && [ $1 -le 65535 ]; then
+			test_port=${SUCCESS}
+		fi 			
+		return ${test_port}
+	}
+
+	#argu: Test_variable:Name_configuration_part_to_test
+	function _test_already_configured() {
+		local _ret=${SUCCESS}
+	
+		if [[ ${1%%:*} -eq ${SUCCESS} ]]; then
+			NOT_DEFINE ${__CMDLINE__} && {
+				${DIALOG} \
+					--colors --title "\Zb\Z1Already Configured\Zn\ZB" --yesno "Already configured:\Zb\Z1${1##*:}\Zn\ZB.\nDo you want to reconfigure?" \
+					$((HEIGHT-7)) $((WIDTH-20))
+				
+				case $? in 
+					${DIALOG_OK}) _ret=${SUCCESS} ;;
+					${DIALOG_CANCEL}) _ret=${FAILURE} ;;
+				esac
+			} || {
+				tput setaf 9
+				echo -en $(get_string_by_name COND_ALREADY_CONFIGURED "${1##*:}[y/N]?")
+				tput sgr0
+				read -n 1 ans
+			
+				case "$ans" in 
+					Y|y) _ret=${SUCCESS} ;;
+					*) _ret=${FAILURE} ;;
+				esac 
+			}
+		fi 
+	
+		return $_ret
+	}
+
+	#argu: test_condition:display_text
+	function _check_configured() {
+		local -a _argu_arr=( $@ )
+		local _configured=${FAILURE}
+		local msg_str=""
+	
+		for (( index=0; index<${#_argu_arr[@]}; index++ )); do 
+			if [[ ${_argu_arr[$index]%%:*} -eq ${FAILURE} ]]; then
+				msg_str+=${_argu_arr[$index]##*:}
+				_configured=${SUCCESS}
+			fi 
+		done 
+	
+		[ ${_configured} -eq ${SUCCESS} ] && {
+			msg_str=${msg_str//_/ }
+			msg_str=${msg_str//|/\\n}
+		
+			NOT_DEFINE ${__CMDLINE__} && { 
+				${DIALOG} \
+					--colors --title "\Zb\Z1 Not Configured Yet\Zn\ZB" --msgbox "You have not configured.\n \Zb\Z1${msg_str}\Zn\ZB." \
+					$((HEIGHT-7)) $((WIDTH-20))		
+			} || { 
+				tput setaf 9
+				echo -en "\nYou have not configured.\n$msg_str"
+				tput sgr0
+			}
 		}
+	
+		return ${_configured}
 	}
 	
-	return ${_configured}
-}
+	##create desktop files
+	#argu name of vm
+	function create_desktop_icon(){
+		local _filename=$(String_to_Lower $1)
+		local _filename="${HOME}/Desktop/${_filename}.desktop"
+		touch ${_filename}
 	
-##create desktop files
-#argu name of vm
-function create_desktop_icon(){
-	local _filename=$(String_to_Lower $1)
-	local _filename="${HOME}/Desktop/${_filename}.desktop"
-	touch ${_filename}
+		echo -e "[Desktop Entry]\nTerminal=true">${_filename}
+		echo -e "Encoding=UTF-8\nType=Application\nIcon=/usr/local/bin/QBox/icon/qbox_shortcut.png\nName=$1\nGenericName=Virtual Machine Manager">>${_filename}
+		echo -e "Exec=sh -c '${QBOX_DIR}/QBox --startvm $1 ;$SHELL'\nComment=QBox for easy management of VMs locally or remotely">>${_filename}
 	
-	echo -e "[Desktop Entry]\nTerminal=true">${_filename}
-	echo -e "Encoding=UTF-8\nType=Application\nIcon=/usr/local/bin/QBox/icon/qbox_shortcut.png\nName=$1\nGenericName=Virtual Machine Manager">>${_filename}
-	echo -e "Exec=sh -c '${QBOX_DIR}/QBox --startvm $1 ;$SHELL'\nComment=QBox for easy management of VMs locally or remotely">>${_filename}
+		chmod 751 ${_filename}
+	}
 	
-	chmod 751 ${_filename}
-}
+	##get the value for a field in the vm bootfile 
+	##argu: id_of_field, file_name, variable_to_set_value_to
+	#ret: success if successful Or failure
+	function get_value_for_field() {
+		local value=""
+		local file_name=$2
+		local value=$(gawk -F "|" -v var="^$1\$" '$1 ~ var {print $2}' ${file_name})
+		
+		[ "$value" != "" ] && { echo -n "$value"; } || { echo -n ""; }
+	}
+
 fi
